### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by DonAkland** [Palmstroemen/WB_Organizer#2]
Great work! Thank you for creating this.

I would like to suggest a couple of things that I would find very useful.
1. Change the code that remembers the last used workbench to remember several recently used workbenches. List them at the top, with the last-used workbench the selected one. Add a separator between this list and the regular list of workbenches.  This feature would be similar to the way Microsoft Word lists fonts in the font selection menu.
2. Add an option to display all of the groups at the same time, with separators between each group. Provide a method for the user to designate groups to include or exclude from this grouped master list.

Best regards,
Don Akland

**Comment by Palmstroemen** [comment]
Hi Don Akland! Thank you for your nice remark and your suggestions.

For the first idea, I see a use case. Indeed, it could be quite useful, to have such a list of last-used workbenches. I'll think of this.

For the second idea. I'm not sure if I understand it correctly. As I understand it, you want an option to display all workbenches of all groups at the same time, with separators between each group. Then you'd like to have an option to hide some groups inside this 'master'-list.

I have already thought of that by myself. I came to the conclusion, that this would kind of counteract the principle idea of the WBO to shorten the long list of workbenches and to avoid scrolling. This would make sense just in the list of 'All' workbenches which at first would even get longer as it is already now because of the additional separators and the fact that a workbench can appear in multiple groups.

Then I think this might confuse users, as they would have to understand this different behaviours of the 'special' group 'All'.

The general idea of this workbench is to get rid of this long group 'All'. It's still there just for completeness to give users the possibility to select workbenches the 'old-fashioned' way, and for giving users access to workbenches they haven't placed manually in a group yet, and that they might just rarely use. I don't really want to 'blow up' this 'All'-group again.

How about simply providing a way to add separator lines to your own groups? Maybe even named separator lines? This way you could design your own 'Master-Group' as you like. But you could also use it to structurize other groups.

Another idea might be to allow for groups inside groups. This way you also could easily build your own 'master'-group with the advantage, that if you make changes inside a 'sub'-group these changes would automatically propagate into your 'master'-group. But I wonder if such things don't make things too complicated for most users.

**Comment by DonAkland** [comment]
My original idea was just to provide for separator lines between “groups” in the WBO All group. Simply providing for separator lines would be sufficient.

 

As I thought more, it occurred to me that the other groups already provide those groupings and it should be simple to have an option to list several of these groups with separators between them, but it also occurred to me that I might not want some of them to show up in the list I use most of the time (for instance, I don’t create PCBs and I don’t have a 3D printer, so it’s unlikely I will use several workbenches). This wouldn’t do away with the WBO All group; it would just be another group.

 

Thanks again,

**Comment by Palmstroemen** [comment]
Hi Don Akland!

You should be able now to manually add separators to your workbenches lists inside a group like so:

    "Construct parts": [
        "DraftWorkbench",
        "PartWorkbench",
        "PartDesignWorkbench",
        "---MySeparator",
        "InventorWorkbench",
        "SMWorkbench",
        "",
        ]
        
Simply write a list-entry with 3 leading '-' like so: '---'. This will generate a separator. 
Unfortunately the text behind ('---MySeparator') will not be shown as of now. I don't know exactly why, but it seems to me that FreeCAD doesn't show any separator labels at all.

Are you aware, that you can hide workbenches by simply removing the checkbox-hook left of the workbench in the preferences of the WBO? This will not delete or remove the workbench. It will not even deactivate it or affect its position in the list. It will simply hide it.

In contrast, if you do so in the original official preferences for workbenches, you'll deactivate the workbench and it will drop to the bottom of the list at the same time.

**Comment by DonAkland** [comment]
Wow! That’s great. I’ll give it a try. And I wasn’t aware I could hide workbenches without removing them. 

 

Thank you very much,

Don

**Comment by DonAkland** [comment]
Thanks for making the change to enable the separator. I have found it to be very useful.

BTW, when I attempt to view your project in the FreeCAD Addon Manager, your homepage is a 404 page not found. It looks like you should change:

https://github.com/Palmstroemen/WB_Organizer.git/raw/main/README.md

 

To: 

https://github.com/Palmstroemen/WB_Organizer/blob/main/README.md

 

 

*	Don Akland

**Comment by Palmstroemen** [comment]
Thank you for the info. I still can't find my WBO in the AddOn-Manager. It seems to be a general problem, that for the moment most AddOns are not shown directly in the AddOn-Manager due to an issue at GitHub.
I for myself, can't change this link. This somehow is made by Chennes from FreeCAD.

**Comment by DonAkland** [comment]
Interesting…your comment caused me to take another look. Your workbench always appears first in my list because the name, ‘1A Workbench Organizer’ that you gave it puts it first in the sorted list. After selecting it, I got the same 404 error. Due to your comment, I thought to click the Refresh Local Cache button. After a brief wait, your readme.md page appeared properly. So that problem is solved and maybe that information will help someone solve the greater problem.

 

BTW, I ran across a couple typos:

1) Preferences dialog. Lenght should be Length in the label, “Lenght of Workbench Organizer when free floating:”.

2) Instructions.txt, last bullet: EXEPT should be EXCEPT in “EXEPT THE LAST LINE”.

 

Something about your WBO: I used to kind of resist changing workbenches—it’s like I would always mutter to myself, “not again”. I’ve noticed since starting to use it, that it’s a lot easier to change workbenches because I don’t have to search a long list for what I need.

**Comment by Palmstroemen** [comment]
Thank you for this interesting information.
It's true, I once called it "1A_WorkbenchOrganizer" to put it in the first place, as I thought, it might be useful to find it easily. But I then was asked by Chennes who is managing these things at FreeCAD to remove the "1A" and so I did.
I'm surprised that it now appears under this name at you. I don't see it at all.

There is a GitHub list, where all AddOns are managed which make it to the AddOn-Manager and I still can't find the WBO there.
https://github.com/FreeCAD/FreeCAD-addons
